name = "RumenSimulation"
uuid = "0bc3709f-ffa8-461e-ab45-2eba68f28c3a"
authors = ["Thomas A. Christensen II <25492070+MillironX@users.noreply.github.com>"]
version = "0.2.0"

[deps]
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Trapz = "592b5752-818d-11e9-1e9a-2b8ca4a44cd1"

[compat]
NLsolve = "4.5.1"
